// function printMessage(message){
//     console.log("message")
// }
// printMessage("hello there")

// var x =10;
// var add = function(a,b){
//     console.log(a+b);
// }
// console.log(typeof add);

var add =function(a,b){
    console.log(a+b);
}
const sub = function(a,b){
    console.log(a-b);
}
function calc(func){
    func(10,10)
}
// function addAndPrintMessage(add, message){
//     add(12,13);

    




calc(add);
calc(sub);













addAndPrintMessage(add,"hello there")
